# Configuration de base pour Mosquitto

# Autoriser les connexions sans mot de passe (pour le développement uniquement !)
allow_anonymous true

# Écouter sur le port standard MQTT
listener 1883 0.0.0.0

# Écouter sur les WebSockets (pour la page web)
listener 9001 0.0.0.0
protocol websockets
